server:
  port: 9090
spring:
  cloud:
    function:
      definition: myFunction
    stream:
      binders:
        #This section of the configuration tells the solace binder how to connect to the solace event broker/mesh
        solace-broker:
          type: solace
          environment:
            solace:
              java:
                host: tcps://solacehost:55443
                msgVpn: spring-cloud-stream
                clientUsername: username
                clientPassword: password
                connectRetries: 3
                connectRetriesPerHost: 0
                reconnectRetries: 3
      bindings:
        myFunction-in-0:
          destination: 'a/b/>'
#          group: exclusive #For exclusive
          group: nonexclusive
          consumer:
            concurrency: 5
        myFunction-out-0:
          destination: 'my/default/topic'
#      solace:
#        bindings:
#          myConsumer-in-0:
#            consumer:
#              queueAdditionalSubscriptions:
#                - 'a/b/>'
#                - 'pub/*/plus'
##              queue-access-type: 1 #1 is Exclusive; 0 is Non-Exclusive (and default)
#
##          mySupplier-out-0:
##            producer:
##              nonserializableHeaderConvertToString: true #Only required if supplier is set

